### PR TITLE
handle multiline configs in write_config

### PR DESCRIPTION
**Pull request by apulich-exos**
This commit fixes https://github.com/databrickslabs/jupyterlab-integration/issues/20
Basically, it just sets flags for:
 - is current line a key-value pair or not
 - does current line contain a key which should be overwritten by config.

It it's not a key-value line, then It skips it if current config key should be overwritten or just writes it "as-is" otherwise.

Honestly, I failed running tests as databrickslabs_jupyterlab.notebook shadows jupyter notebook package. Could you please give some more info on how do you run it usually?

### CODE REVIEW

**Comment by bernhard-42** [comment]
@apulich-exos Thanks for coming up with a pull request for this bug. Really appreciated.

While it solves the issue with multiline configs, there might be still an issue with `=` being part of config strings, e.g. someone could have a `=` in `Application.log_formatUnicode` or `NotebookApp.cookie_secretBytes` or so. 

This has nothing to do with your change, the root cause is simply my bad first implementation of `write_config` :(

However, if we fix the bug you've found I feel we should get more robust. So maybe we should change the logic completely to: 
- simply copy every line that does not start with `c.KernelManager.autorestart\s*=` or `c.MappingKernelManager.kernel_info_timeout\s*=`
- If it starts with one of the two config strings, split at `=`, check the value and replace if necessary.
- If one or both of the config strings haven't been found, add them at the end

I would hope that by going this way, the number of potential pitfalls (I usually don't like hacking around in python files, however `jupyterlab_integration` needs these settings to be stable) should be really small.
Does this make sense?


From a test perspective, I just ran the tests as described in the Release.md, and it worked.
So, where did you run into the notebook shadowing issue?

**Comment by apulich-exos** [comment]
Makes sense, that the case I didn't think about for some reason.

> simply copy every line that does not start with c.KernelManager.autorestart\s*= or c.MappingKernelManager.kernel_info_timeout\s*=
I would rather work with that config dict than with hardcoded 2 keys as it's more flexible in case if you decide to overwrite any new configs in the lib. But I got your idea.

As to tests, let me just retry to run them according to the Release.md, maybe I misconfigured something locally. I'll reach you if there are some issues. Thank you.

**Comment by apulich-exos** [comment]
Another quick option without refactoring is just to add key check to the code from this PR like:
```python
k, v = kv
is_key_value_pair = True if k.startswith('c.') else False
```
In this case even if we have configs like below we won't consider `'headers' = dict(` as an independent config line.
```
c.foo = 'bar'
c.NotebookApp.tornado_settings = dict(
   'headers' = dict(
        SOME_HEADER = 'SOME_VALUE'
    )
)
c.bar = True
```

As to tests:
1. I add path to the source code to $PYTHONPATH as otherwise it fails with `ModuleNotFoundError: No module named 'databrickslabs_jupyterlab'`
2. Then I run pytest from the project root or from the tests dir. Both fail with 
```
../databrickslabs_jupyterlab/__init__.py:2: in <module>
    from notebook.utils import url_path_join
E   ModuleNotFoundError: No module named 'notebook'
```

**Comment by bernhard-42** [comment]
I tried to think about more special cases and this is what I would come up with.
Do I still miss anything? What do you think?

```python
def write_config():
    """Store jupyter lab configuration necessary for databrickslabs_jupyterlab
    Set values:
    - c.KernelManager.autorestart: False
    - c.MappingKernelManager.kernel_info_timeout: 600
    """
    config = {
        "c.KernelManager.autorestart": False,
        "c.MappingKernelManager.kernel_info_timeout": 20,
    }
    c1, c2 = list(config.keys())

    full_path = os.path.expanduser("~/.jupyter")
    if not os.path.exists(full_path):
        os.mkdir(full_path)

    config_file = os.path.join(full_path, "jupyter_notebook_config.py")

    lines = []
    if os.path.exists(config_file):
        with open(config_file, "r") as fd:
            lines = fd.read().split("\n")

            # avoid growing by one empty line for each run
            if lines[-1] == "":
                lines = lines[:-1]

    with open(config_file, "w") as fd:
        for line in lines:
            if line.startswith(c1) or line.startswith(c2):
                kv = line.split("=")
                k = kv[0].strip()
                if config.get(k) is not None:  #  if None it's a duplicate, so ignore
                    fd.write("%s = %s\n" % (k, config[k]))
                    del config[k]
                continue

            # else just copy line
            fd.write("%s\n" % line)

        # write all missing configs
        fd.write("\n".join(["%s = %s" % (k, v) for k, v in config.items()]))
```

**Comment by apulich-exos** [comment]
1. There could be empty lines in the middle of a config file. Maybe there is some sense to replace this
```python
    if os.path.exists(config_file):
        with open(config_file, "r") as fd:
            lines = fd.read().split("\n")

            # avoid growing by one empty line for each run
            if lines[-1] == "":
                lines = lines[:-1]
```
with something like this:
```python
    if os.path.exists(config_file):
        with open(config_file, "r") as fd:
            lines = [line for line in fd if line != '']
```

2. As to writing to the final config file, seems ok, but only if you don't plan to add some keys to config dict values for which could be multiline.  As c.KernelManager.autorestart and c.MappingKernelManager.kernel_info_timeout are simply a bool and an int, then we shouldn't face any problems. If you don't mind, I guess we can merge it and I can try to make it more universal in my free time.

**Comment by bernhard-42** [comment]
I have no plans for further enhancements of this. The two keys were necessary, but I don't want to fiddle more with this.
Reason why I kept empty lines was to keep the structure as similar to the original as possible. Maybe somebody used empty lines to structure the logical blocks.

I'm happy that you take over the current state and improve it more. Please let me know how I can help.
Thanks!

**Comment by apulich-exos** [comment]
Makes sense, let's keep empty lines and use your version as it is now. Thank you! I can update the PR this week then.

**Comment by apulich-exos** [comment]
@bernhard-42 Added your suggested version to the branch

**Review by bernhard-42 — APPROVED** [review]

**Pull request merged**
